#!/usr/bin/env node

const program = require('commander');
const clear = require('clear');
const chalk = require('chalk');
const figlet = require('figlet');
const packageJson = require('../package.json');

// Lets clear the console
clear();

// banner of the cli
console.info(
  chalk.yellow(figlet.textSync(packageJson.name, {horizontalLayout: 'full'}))
);
console.info(chalk.cyan('Version: ' + packageJson.version));


program
  .version(packageJson.version)
  .description(packageJson.description)
  .command('s3 <srcDirectory> <bucketName>', 'Deploys the static website directory to s3 bucket with sync')
  .command('invalidate-cache <cloudfrontId>', 'Invalidates the cloudfront cache')
  .command('lambda', 'Manage the lambda deployment')
  .parse(process.argv);

// dispay the usage
if (!program.args.length) program.help();
