#!/usr/bin/env node

const program = require('commander');

// lambda command
program
  .name('lambda')
  .command('update <lambdaName>', 'Update the lambda function code')
  .command('version', 'Displays the currnt lambda function code version')
  .parse(process.argv);
