#!/usr/bin/env node

const { Command } = require("commander");
import { CloudFrontClient } from "@aws-sdk/client-cloudfront";
const { fromNodeProviderChain } = require("@aws-sdk/credential-providers");
const Logger = require("../libs/logger.js");
const CacheInvalidate = require("../libs/cf-invalidate.js");

const logger = new Logger();
const program = new Command();

/**
 * callback to collect the multiple instances of same argument options
 *
 * @param {String} val A value of argument option
 * @param {Array} memo An array
 * @return {Array} An array containing all values of argument option
 */
function collect(val, memo) {
  memo.push(val);
  return memo;
}

// invalidate the cloudfront Cache
program
  .name("invalidate-cache")
  .usage("[options] <cloudfrontId>")
  .arguments("<cloudfrontId>")
  .option("--profile <profileName>", "AWS credential profile name")
  .option("--region <regionName>", "AWS region name", "us-east-1")
  .option(
    "--path [value]",
    "A repeatable value of path that needs the invalidation",
    collect,
    [],
  )
  .option("--debug", "Log extra debug information")
  .action(function (cloudfrontId, options) {
    logger.info("Invalidating the cache for cloudfront id: " + cloudfrontId);
    if (options.profile !== undefined) {
      credentials = fromNodeProviderChain({
        profile: options.profile,
      });
    } else {
      credentials = fromNodeProviderChain();
    }
    const client = new CloudFrontClient({
      region: options.region,
      credentials,
    });
    let cacheInvalidate = new CacheInvalidate(client);
    try {
      cacheInvalidate.invalidate(cloudfrontId, options);
    } catch (exception) {
      logger.error(exception);
      process.exit(1);
    }
  })
  .parse(process.argv);

// display the usage
if (!program.args.length && program.args.length < 2) program.help();
