#!/usr/bin/env node

const { Command } = require("commander");

const program = new Command();

// lambda command
program
  .name("lambda")
  .command(
    "build <outputZipFileName>",
    "creates the build file for AWS lambda deployment",
  )
  .command(
    "update <functionName> <zipFilePath>",
    "Update the lambda function code",
  )
  .command("version", "Displays the current lambda function code version")
  .parse(process.argv);
