#!/usr/bin/env node

const program = require('commander');
const AWS = require('aws-sdk');
const S3Deploy = require('../libs/s3-deploy.js');
const Logger = require('../libs/logger.js');

const logger = new Logger();

// deploy command
program
  .name('s3')
  .usage('[options] <srcDirectory> <bucketName> ')
  .arguments('<srcDirectory> <bucketName>')
  .option('--profile <profileName>', 'AWS credential profile name')
  .option('--region <regionName>', 'AWS region name', 'us-east-1')
  .option(
    '--delete',
    'Files that exist in the destination but not in the source are deleted during sync'
  )
  .option('--debug', 'Log extra debug information')
  .action(function(srcDirectory, bucketName, options) {
    const message =
      'Deploying from ' + srcDirectory + ' to s3 bucket ' + bucketName;
    logger.info(message);
    AWS.config.update({region: options.region});
    if (options.profile !== undefined) {
      let credentials = new AWS.SharedIniFileCredentials({
        profile: options.profile,
      });
      AWS.config.credentials = credentials;
    }
    let s3 = new AWS.S3();
    let s3deploy = new S3Deploy(s3);
    try {
      s3deploy.syncBucket(srcDirectory, bucketName, options);
    } catch (exception) {
      logger.error(exception.message);
      process.exit(1);
    }
  })
  .parse(process.argv);

// dispay the usage
if (!program.args.length && program.args.length < 3) program.help();
